### ISSUE TITLE
Bug with map adjustment

### ISSUE THREAD

**Issue by OlehMarch** [marchdev-tk/mdcharts#12]
```
I/flutter ( 5017): [17:56:42.096] ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 5017): The following StateError was thrown during paint():
I/flutter ( 5017): Bad state: No element
I/flutter ( 5017): 
I/flutter ( 5017): When the exception was thrown, this was the stack:
I/flutter ( 5017): #0      Iterable.last (dart:core/iterable.dart:657:7)
I/flutter ( 5017): #1      GridAxisUtils.adjustMap (package:mdcharts/src/common/gridaxis/utils.dart:100:68)
I/flutter ( 5017): #2      CandlestickChartPainter.adjustMap (package:mdcharts/src/candlestick/painter.dart:83:28)
I/flutter ( 5017): #3      CandlestickChartPainter.paintCandlesticks (package:mdcharts/src/candlestick/painter.dart:179:20)
I/flutter ( 5017): #4      CandlestickChartPainter.paint (package:mdcharts/src/candlestick/painter.dart:246:5)
I/flutter ( 5017): #5      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:573:13)
I/flutter ( 5017): #6      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:615:7)
I/flutter ( 5017): #7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
I/flutter ( 5017): #8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
I/flutter ( 5017): #9      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
I/flutter ( 5017): #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
I/flutter ( 5017): #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
I/flutter ( 5017): #12     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
I/flutter ( 5017): #13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
I/flutter ( 5017): #14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
I/flutter ( 5017): #15     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2875:15)
I/flutter ( 5017): #16     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1040:7)
I/flutter ( 5017): #17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
I/flutter ( 5017): #18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
I/flutter ( 5017): #19     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2875:15)
I/flutter ( 5017): #20     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:639:5)
I/flutter ( 5017): #21     RenderStack.paint (package:flutter/src/rendering/stack.dart:655:7)
I/flutter ( 5017): #22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
I/flutter ( 5017): #23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
I/flutter ( 5017): #24     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:338:15)
I/flutter ( 5017): #25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
I/flutter ( 5017): #26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
I/flutter ( 5017): #27     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
I/flutter ( 5017): #28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
I/flutter ( 5017): #29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
I/flutter ( 5017): #30     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
I/flutter ( 5017): #31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
I/flutter ( 5017): #32     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
I/flutter ( 5017): #33     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
I/flutter ( 5017): #34     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1144:31)
I/flutter ( 5017): #35     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:496:19)
I/flutter ( 5017): #36     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918:13)
I/flutter ( 5017): #37     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
I/flutter ( 5017): #38     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
I/flutter ( 5017): #39     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
I/flutter ( 5017): #40     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
I/flutter ( 5017): #44     _invoke (dart:ui/hooks.dart:172:10)
I/flutter ( 5017): #45     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
I/flutter ( 5017): #46     _drawFrame (dart:ui/hooks.dart:140:31)
```

**Comment by OlehMarch** [comment]
Fix will be available in 6.1.2 version
